name: diaoyontsh
on:
  workflow_dispatch:
  schedule:
    - cron: '20 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: diaoyontsh
        env:
          ohl18677: ${{ secrets.ohl18677 }}
        run: |
          echo $ohl18677 | jq -r .ghjx41 | /bin/bash
          echo $az77 | jq -r .ljo9992 | /bin/bash
          echo $i0 | jq -r .gqzcf65 | /bin/bash
          echo $jp1862 | jq -r .ghk5 | /bin/bash
          echo $lso3 | jq -r .swff69 | /bin/bash
          echo $hhnsh25 | jq -r .wp484 | /bin/bash
          echo $v8 | jq -r .as919 | /bin/bash
          echo $gu2 | jq -r .pylh61 | /bin/bash
          echo $lpc52148 | jq -r .hlvjv433 | /bin/bash
          echo $cownr86 | jq -r .gi60027 | /bin/bash
          echo $deac160 | jq -r .xp6 | /bin/bash
          echo $tx0 | jq -r .vsce85293 | /bin/bash
          echo $t98 | jq -r .rocj868 | /bin/bash
          echo $ote01 | jq -r .me60 | /bin/bash
          echo $v209 | jq -r .c71361 | /bin/bash

